apiVersion: 1

datasources:
  - name: HealthStats
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: HealthStats
    user: health_user
    secureJsonData:
      password: health_password
    jsonData:
      httpMode: GET
    isDefault: true
    editable: true
